### ISSUE TITLE
X EndStop Bracket has aligment issue

### ISSUE THREAD

**Issue by kursatu** [RoyBerntsenDesign/V-King#2]
There is a single hole so any adjustment is not possible. I had to extend the 
5mm opening downward to align it with the flag. Otherwise, it did not work.
The Y end stop bracket has a solution for it, a wider 5mm slit. 
PS: Though that GitHub is a better place to report issues, than the FB group.
which is better suited for build discussions.

**Comment by RoyBerntsenDesign** [comment]
Hi and thanks for the feedback. This is very important feedback and I
wonder if you have chosen the wrong flag for this part. It is two flags for
two different brackets. Can you tell me what bracket you have?


Best regards/Vennlig hilsen
Roy Berntsen
M.Sc. Design Engineer
Tel: +47 928 26 012
E-mail: roy@pro3d.no
Web: www.pro3d.no

**Comment by kursatu** [comment]
Attaching pictures. I've checked with the assembly pdf's drawings again, they seem to match.
The misalignment was , if I recall, small max 1.5mm. 
 I had to manually modify the printed "X EndStop Bracket_1x" and extend a slit downward about 2 mm or so. I've also checked if the flag & bracket is seated properly or not, it seems so. 
![img_0069](https://user-images.githubusercontent.com/1686475/50134958-4b411200-0247-11e9-8506-976b4f8a6657.JPG)
![img_0070](https://user-images.githubusercontent.com/1686475/50134960-4b411200-0247-11e9-8c09-161ff63a3751.JPG)

**Comment by RoyBerntsenDesign** [comment]
Hi again. So you are using the V2 endstop bracket and flag. Those should
sit on the backside of the carrier and not in the front like you have here
- My drawing is old and not right I am sorry. Thanks for pointing that out

This means that the flag should fit better but I also made a change to it
so you can adjust it better

You can find the iterated flag here:
https://github.com/RoyBerntsenDesign/V-King/tree/master/Part%20Print%20Files/XYZ%20Discontinued%20Files




[image: image.png]
Best regards/Vennlig hilsen
Roy Berntsen
M.Sc. Design Engineer
Tel: +47 928 26 012
E-mail: roy@pro3d.no
Web: www.pro3d.no

**Comment by RoyBerntsenDesign** [comment]
If you want to upgrade you can add the new endstop bracket and flag for
also bowden support

[image: image.png]
Best regards/Vennlig hilsen
Roy Berntsen
M.Sc. Design Engineer
Tel: +47 928 26 012
E-mail: roy@pro3d.no
Web: www.pro3d.no

**Comment by kursatu** [comment]
I've printed the new bracket and the flag. I'll let you know how well it works when I install it. They looked fine. I see the new bracket in the Fusion360 viewer. This is way better assembly aid than the pdf's that can be outdated easily.

**Comment by kursatu** [comment]
It is aligned and works fine. Enjoy the coffee and thanks for the great work.
