### ISSUE TITLE
Wrong bolt size on Y carrier to XY idler ASY in drawings and in BoM

### ISSUE THREAD

**Issue by martinroger** [RoyBerntsenDesign/V-King#3]
The bolts in the drawing "Y-slider drawing" #12 that join the Y carriers to their respective XY idlers is indicated as M4x10, and in the most recent online assembly they are actually M5x14. The BoM does not list any M5x14, but does mention some M5x12. Unfortunately the M5x12 can barely catch one thread of the T-nut on the other side.

The correct size should be M5x14, Qty 4 minimum in the BOM. M5x16 might also work, but it is unverified.

<img width="892" alt="capture d ecran 2019-02-20 a 23 12 10" src="https://user-images.githubusercontent.com/11090574/53128986-912b9680-3566-11e9-8ca9-7ec5e681cca2.png">

**Comment by RoyBerntsenDesign** [comment]
Thanks for pointing this out. The brackets was redesignen and I never got
to change the bom... I will do  that this weekend


Best regards/Vennlig hilsen
Roy Berntsen
M.Sc. Design Engineer
Tel: +47 928 26 012
E-mail: roy@pro3d.no
Web: www.pro3d.no

**Comment by RoyBerntsenDesign** [comment]
Updated the BOM with M5x14
